"""Added: conversation > v3 > categories > sub-categories sub_category table

Revision ID: 0085bfaf40cb
Revises: 8865c528824c
Create Date: 2024-07-21 10:39:08.229079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0085bfaf40cb'
down_revision: Union[str, None] = '8865c528824c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
