"""Added: social-media > conversation > categories category table

Revision ID: 01899fde741c
Revises: 8ba96d370e07
Create Date: 2024-07-22 21:02:10.339911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01899fde741c'
down_revision: Union[str, None] = '8ba96d370e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
