"""Added: social-media > conversation > categories category table

Revision ID: 0664ab902260
Revises: abb9dda5cfda
Create Date: 2024-07-23 21:08:15.446845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0664ab902260'
down_revision: Union[str, None] = 'abb9dda5cfda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
