"""Added: conversation > v3 > categories > sub-categories > questions question table

Revision ID: 08b17632e6e1
Revises: 7d40dce9b8cc
Create Date: 2024-07-20 21:54:45.187690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b17632e6e1'
down_revision: Union[str, None] = '7d40dce9b8cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
