"""Added: auto-builders > model-builder model_builder table

Revision ID: 08fbc26d3f82
Revises: 103e58b74622
Create Date: 2024-07-25 20:53:32.765323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08fbc26d3f82'
down_revision: Union[str, None] = '103e58b74622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
