"""Added: Company company table

Revision ID: 0b0c7a82e7d5
Revises: 73a88328971b
Create Date: 2025-04-16 17:16:48.241192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0b0c7a82e7d5'
down_revision: Union[str, None] = '73a88328971b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('number_of_employees', sa.Integer(), nullable=True))
    op.drop_column('companies', 'Number_of_employees')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('Number_of_employees', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('companies', 'number_of_employees')
    # ### end Alembic commands ###
