"""Added: conversation > v3 > categories > sub-categories > questions question table

Revision ID: 0bbd426facaf
Revises: 72a6de0ad0ed
Create Date: 2024-07-21 00:51:16.095266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bbd426facaf'
down_revision: Union[str, None] = '72a6de0ad0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
