"""Added: auto-builders > model-builder > model-headers model_header table

Revision ID: 0bf8cb234836
Revises: 4dbc5ccf435f
Create Date: 2024-07-26 02:28:17.958281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bf8cb234836'
down_revision: Union[str, None] = '4dbc5ccf435f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
