"""Added: customers customer table

Revision ID: 0c01e4e305a1
Revises: b89d635e2d4d
Create Date: 2024-07-22 09:38:55.999943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c01e4e305a1'
down_revision: Union[str, None] = 'b89d635e2d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
