"""Added: conversation > v3 > categories > sub-categories sub_category table

Revision ID: 0eef3c46a25a
Revises: 1221a348d08a
Create Date: 2024-07-21 01:16:00.167196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eef3c46a25a'
down_revision: Union[str, None] = '1221a348d08a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
