"""Added: auto-builders > model-builder model_builder table

Revision ID: 103e58b74622
Revises: 2780886685e1
Create Date: 2024-07-25 20:52:48.009446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '103e58b74622'
down_revision: Union[str, None] = '2780886685e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
