"""added sys_opportunities_creator table

Revision ID: 10c149ca9482
Revises: c0b5c3169f13
Create Date: 2024-07-03 17:56:09.133196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c149ca9482'
down_revision: Union[str, None] = 'c0b5c3169f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
