"""Added: auto-builders > model-builder > model-fields model_field table

Revision ID: 11036661a3a2
Revises: 1fd300d263ed
Create Date: 2024-07-26 02:22:59.778441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11036661a3a2'
down_revision: Union[str, None] = '1fd300d263ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
