"""Added: conversation > v3 > categories > sub-categories sub_category table

Revision ID: 1221a348d08a
Revises: 5ec661a211ce
Create Date: 2024-07-21 01:15:07.206054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1221a348d08a'
down_revision: Union[str, None] = '5ec661a211ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
