"""Added: conversation > v3 > messages message table

Revision ID: 1270b058e04f
Revises: df5806ab0a7b
Create Date: 2024-07-20 13:26:17.553211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1270b058e04f'
down_revision: Union[str, None] = 'df5806ab0a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_v3_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('sub_category_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('mode', sa.String(length=255), nullable=True),
    sa.Column('interview_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('question_scores', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('audio_uri', sa.String(length=255), nullable=True),
    sa.Column('status_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['conversation_v3_categories.id'], ),
    sa.ForeignKeyConstraint(['interview_id'], ['conversation_v3_interviews.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['conversation_v3_categories_sub_categories_questions.id'], ),
    sa.ForeignKeyConstraint(['sub_category_id'], ['conversation_v3_categories_sub_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_v3_messages')
    # ### end Alembic commands ###
