"""Added: social-media > conversation > categories category table

Revision ID: 13834c93db7f
Revises: d1bc44e50bac
Create Date: 2024-08-21 22:05:05.546802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13834c93db7f'
down_revision: Union[str, None] = 'd1bc44e50bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
