"""Added: social-media > conversation > categories > sub-categories > questions question table

Revision ID: 13b6505c5b61
Revises: f9fdfc56dd65
Create Date: 2024-07-27 18:47:07.074111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13b6505c5b61'
down_revision: Union[str, None] = 'f9fdfc56dd65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soc4bversation_categories_sub_categories_questions', sa.Column('question', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('soc4bversation_categories_sub_categories_questions', 'question')
    # ### end Alembic commands ###
