"""Added: auto-builders > model-builder model_builder table

Revision ID: 142e669513c9
Revises: e12850120fc3
Create Date: 2024-07-25 20:37:00.733706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142e669513c9'
down_revision: Union[str, None] = 'e12850120fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
