"""Added: social-media > conversation > categories > sub-categories sub_category table

Revision ID: 14f70205158a
Revises: 1d443623702d
Create Date: 2024-07-28 11:17:04.872706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f70205158a'
down_revision: Union[str, None] = '1d443623702d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='soc7e_media_conversation_categories_sub_categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'soc7e_media_conversation_categories_sub_categories', ['name'], unique=True)
    # ### end Alembic commands ###
