"""Added: conversation > v2 > categories category table

Revision ID: 15333448f05e
Revises: 1b13e198457c
Create Date: 2024-07-18 17:27:19.746726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15333448f05e'
down_revision: Union[str, None] = '1b13e198457c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
