"""Added: admin > auto-builders > model-builder > action-labels action_label table

Revision ID: 16c0378254b0
Revises: 7f46a2f1b0d1
Create Date: 2024-07-21 19:56:09.289853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16c0378254b0'
down_revision: Union[str, None] = '7f46a2f1b0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
