"""Added: conversation > v3 > categories > sub-categories > questions question table

Revision ID: 17405622643b
Revises: 08b17632e6e1
Create Date: 2024-07-20 21:58:45.242943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17405622643b'
down_revision: Union[str, None] = '08b17632e6e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
