"""Added: auto-builders > model-builder > model-fields model_field table

Revision ID: 1a01f20be898
Revises: 42d9ed9f81f6
Create Date: 2024-07-26 02:17:19.302553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a01f20be898'
down_revision: Union[str, None] = '42d9ed9f81f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
