"""Added: auto-builders > model-builder model_builder table

Revision ID: 1ad764404e1d
Revises: c9297081ea08
Create Date: 2024-07-25 20:38:20.550687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad764404e1d'
down_revision: Union[str, None] = 'c9297081ea08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
