"""Added: conversation > v2 > categories category table

Revision ID: 1b13e198457c
Revises: f5f6a1e60b63
Create Date: 2024-07-18 17:26:46.029949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b13e198457c'
down_revision: Union[str, None] = 'f5f6a1e60b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
