"""Added: auto-builders > model-builder model_builder table

Revision ID: 1d4208177e4d
Revises: 44162a83aa0d
Create Date: 2024-07-25 20:50:28.973972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d4208177e4d'
down_revision: Union[str, None] = '44162a83aa0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
