"""Added: social-media > conversation > messages message table

Revision ID: 1d443623702d
Revises: edd2790cc060
Create Date: 2024-07-28 02:45:06.064951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1d443623702d'
down_revision: Union[str, None] = 'edd2790cc060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('social_media_conversation_messages', 'audio_uri',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('social_media_conversation_messages', 'audio_uri',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
