"""Added: conversation > v2 > interviews interview table

Revision ID: 1db3256ad57f
Revises: 871e8df64cdd
Create Date: 2024-07-16 12:01:18.662565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db3256ad57f'
down_revision: Union[str, None] = '871e8df64cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_v2_interviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('sub_category_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('scores', sa.Integer(), nullable=True),
    sa.Column('max_scores', sa.Integer(), nullable=True),
    sa.Column('percentage_score', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['conversation_v2_categories.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['conversation_v2_categories_sub_categories_questions.id'], ),
    sa.ForeignKeyConstraint(['sub_category_id'], ['conversation_v2_categories_sub_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_v2_interviews')
    # ### end Alembic commands ###
