"""Added: social-media > conversation > categories > sub-categories > questions question table

Revision ID: 1eb1db3b280b
Revises: b83631591fe5
Create Date: 2024-08-24 14:07:24.499497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb1db3b280b'
down_revision: Union[str, None] = 'b83631591fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
