"""added sys_opportunities_creator table

Revision ID: 1f7448b0a53b
Revises: d7ffd441a63f
Create Date: 2024-07-03 17:58:37.983617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f7448b0a53b'
down_revision: Union[str, None] = 'd7ffd441a63f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
