"""Added: ProjectHistory projecthistory table

Revision ID: 21397bd0bc69
Revises: 561781e1a54b
Create Date: 2025-04-16 21:32:33.600940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21397bd0bc69'
down_revision: Union[str, None] = '561781e1a54b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
