"""Added: admin > auto-builders > model-builder > model-fields model_field table

Revision ID: 2201d8904069
Revises: daee536bd9dd
Create Date: 2024-07-21 18:42:22.826687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2201d8904069'
down_revision: Union[str, None] = 'daee536bd9dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_auto_builders_model_builder_model_fields', 'isVisibleInList',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('admin_auto_builders_model_builder_model_fields', 'isVisibleInSingleView',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('admin_auto_builders_model_builder_model_fields', 'isRequired',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('admin_auto_builders_model_builder_model_fields', 'isUnique',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_auto_builders_model_builder_model_fields', 'isUnique',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('admin_auto_builders_model_builder_model_fields', 'isRequired',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('admin_auto_builders_model_builder_model_fields', 'isVisibleInSingleView',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('admin_auto_builders_model_builder_model_fields', 'isVisibleInList',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
