"""Added: conversation > v3 > categories > sub-categories sub_category table

Revision ID: 22bd0b9aee7a
Revises: 0915ccee64f6
Create Date: 2024-07-21 11:04:24.826887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22bd0b9aee7a'
down_revision: Union[str, None] = '0915ccee64f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
