"""Added: admin > auto-builders > model-builder > model-fields model_field table

Revision ID: 22c46375b340
Revises: a659140cac2b
Create Date: 2024-07-21 19:52:42.335759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c46375b340'
down_revision: Union[str, None] = 'a659140cac2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
