"""added sys_opportunities_creator table

Revision ID: 24135fa3291f
Revises: a0e4674ca292
Create Date: 2024-07-03 17:38:39.572956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24135fa3291f'
down_revision: Union[str, None] = 'a0e4674ca292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
