"""Added: admin > auto-builders > model-builder model_builder table

Revision ID: 25381d88aad0
Revises: 527ff698bc31
Create Date: 2024-07-21 19:10:36.264800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25381d88aad0'
down_revision: Union[str, None] = '527ff698bc31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
