"""Added: conversation > v3 > categories category table

Revision ID: 25e43a2fe82d
Revises: b40674b3d5c8
Create Date: 2024-07-20 21:09:53.608510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25e43a2fe82d'
down_revision: Union[str, None] = 'b40674b3d5c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
