"""Added rships

Revision ID: 26fbf5dbf04c
Revises: 370917ca5b76
Create Date: 2024-07-16 21:31:50.584378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '26fbf5dbf04c'
down_revision: Union[str, None] = '370917ca5b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_v2_interviews', sa.Column('current_question_id', sa.Integer(), nullable=True))
    op.drop_constraint('conversation_v2_interviews_ibfk_2', 'conversation_v2_interviews', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_v2_interviews', 'conversation_v2_categories_sub_categories_questions', ['current_question_id'], ['id'])
    op.drop_column('conversation_v2_interviews', 'question_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_v2_interviews', sa.Column('question_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'conversation_v2_interviews', type_='foreignkey')
    op.create_foreign_key('conversation_v2_interviews_ibfk_2', 'conversation_v2_interviews', 'conversation_v2_categories_sub_categories_questions', ['question_id'], ['id'])
    op.drop_column('conversation_v2_interviews', 'current_question_id')
    # ### end Alembic commands ###
