"""Added: auto-builders > model-builder model_builder table

Revision ID: 2780886685e1
Revises: 66bd35e8f411
Create Date: 2024-07-25 20:51:49.505493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2780886685e1'
down_revision: Union[str, None] = '66bd35e8f411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
