"""Added: social-media > conversation > categories > sub-categories > questions question table

Revision ID: 278a0e8021f0
Revises: 7c8422e4d16b
Create Date: 2024-07-23 21:43:59.676458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '278a0e8021f0'
down_revision: Union[str, None] = '7c8422e4d16b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
