"""Added: conversation > v3 > categories category table

Revision ID: 291b4fe3be52
Revises: 6f8c5a88108e
Create Date: 2024-07-21 00:49:31.990968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '291b4fe3be52'
down_revision: Union[str, None] = '6f8c5a88108e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
