"""Added: auto-builders > model-builder > model-fields model_field table

Revision ID: 2aa207ff1fa3
Revises: ac4fc76eb8f4
Create Date: 2024-07-26 02:29:17.182383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa207ff1fa3'
down_revision: Union[str, None] = 'ac4fc76eb8f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
