"""Added: social-media > conversation > categories > sub-categories sub_category table

Revision ID: 2ee96b95213d
Revises: ddb48f84e6ea
Create Date: 2024-07-22 23:51:45.341653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee96b95213d'
down_revision: Union[str, None] = 'ddb48f84e6ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
