"""Added: social-media > conversation > categories > sub-categories sub-category table

Revision ID: 2f7a184bd53a
Revises: 8aa1563ba67d
Create Date: 2024-07-22 22:37:04.247342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f7a184bd53a'
down_revision: Union[str, None] = '8aa1563ba67d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
