"""Added: social-media > conversation > messages message table

Revision ID: 2f86dac39811
Revises: ebe1bd6426fa
Create Date: 2024-07-27 21:31:00.424941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f86dac39811'
down_revision: Union[str, None] = 'ebe1bd6426fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
