"""Added: auto-builders > model-builder model_builder table

Revision ID: 35db0033b5be
Revises: d61fc7a91f08
Create Date: 2024-07-26 01:23:38.954909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35db0033b5be'
down_revision: Union[str, None] = 'd61fc7a91f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
