"""Added: admin > users user table

Revision ID: 370917ca5b76
Revises: 46ebc1ed5169
Create Date: 2024-07-16 19:30:32.609480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370917ca5b76'
down_revision: Union[str, None] = '46ebc1ed5169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admin_users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_users', type_='unique')
    # ### end Alembic commands ###
