"""Added: conversation > v3 > categories > sub-categories > questions question table

Revision ID: 3732432c516d
Revises: 5002de22b56f
Create Date: 2024-07-18 21:11:53.767719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3732432c516d'
down_revision: Union[str, None] = '5002de22b56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
