"""Added: conversation > v3 > categories > sub-categories sub_category table

Revision ID: 37a7c8f9de65
Revises: 87c9fa2332cb
Create Date: 2024-07-21 01:25:23.175454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a7c8f9de65'
down_revision: Union[str, None] = '87c9fa2332cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
