"""Added: social-media > conversation > categories category table

Revision ID: 38f89fac4e8c
Revises: 2717e39fc606
Create Date: 2024-08-21 22:25:13.261922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38f89fac4e8c'
down_revision: Union[str, None] = '2717e39fc606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
