"""Added: auto-builders > model-builder model_builder table

Revision ID: 39675937d2c0
Revises: 1b1c9c14971d
Create Date: 2024-07-27 18:03:55.414838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39675937d2c0'
down_revision: Union[str, None] = '1b1c9c14971d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
