"""Added: auto-builders > model-builder model_builder table

Revision ID: 3a2353962665
Revises: 1ad764404e1d
Create Date: 2024-07-25 20:42:01.521192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a2353962665'
down_revision: Union[str, None] = '1ad764404e1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
