"""Added: admin > auto-builders > model-builder model_builder table

Revision ID: 3bd0bcbb7e6f
Revises: 829bbf2a650d
Create Date: 2024-07-21 19:05:42.101249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd0bcbb7e6f'
down_revision: Union[str, None] = '829bbf2a650d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
