"""Added: conversation > categories category table

Revision ID: 3c04bb84f996
Revises: eda71c7f1fc6
Create Date: 2024-07-21 21:31:32.157699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c04bb84f996'
down_revision: Union[str, None] = 'eda71c7f1fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
