"""Added: auto-builders > model-builder > model-headers model_header table

Revision ID: 3ff59ce631cc
Revises: d591b07a9164
Create Date: 2024-07-27 18:16:23.982580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff59ce631cc'
down_revision: Union[str, None] = 'd591b07a9164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
