"""Added: auto-builders > model-builder model_builder table

Revision ID: 3ffd528681a9
Revises: aa712965ec4a
Create Date: 2024-07-27 15:40:04.893340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ffd528681a9'
down_revision: Union[str, None] = 'aa712965ec4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
