"""Added:  > api > email-providers emailprovider table

Revision ID: 402a587a8805
Revises: 72a2bf85e28e
Create Date: 2025-04-17 09:07:51.899544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '402a587a8805'
down_revision: Union[str, None] = '72a2bf85e28e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_email_providers_emailproviders', sa.Column('location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_email_providers_emailproviders', 'location')
    # ### end Alembic commands ###
