"""Added: conversation > v3 > categories category table

Revision ID: 412f94375a52
Revises: 4dd66cc6c0ae
Create Date: 2024-07-21 03:51:57.012654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '412f94375a52'
down_revision: Union[str, None] = '4dd66cc6c0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
