"""Added: admin > auto-builders > model-builder > model-fields model_field table

Revision ID: 41455b7f1def
Revises: 25381d88aad0
Create Date: 2024-07-21 19:47:30.308966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41455b7f1def'
down_revision: Union[str, None] = '25381d88aad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
