"""Added: auto-builders > model-builder > model-headers model_header table

Revision ID: 42d9ed9f81f6
Revises: fa2fbdba55c7
Create Date: 2024-07-26 02:17:02.820097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42d9ed9f81f6'
down_revision: Union[str, None] = 'fa2fbdba55c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
