"""Added: conversation > v3 > categories category table

Revision ID: 450e2cf4ef90
Revises: 412f94375a52
Create Date: 2024-07-21 03:52:47.697308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '450e2cf4ef90'
down_revision: Union[str, None] = '412f94375a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
