"""Added: conversation > categories category table

Revision ID: 45c2a748eb0d
Revises: 6b0e91e3f1ed
Create Date: 2024-07-21 21:25:45.410956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c2a748eb0d'
down_revision: Union[str, None] = '6b0e91e3f1ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
