"""Added: auto-builders > model-builder model_builder table

Revision ID: 466a3bd8e249
Revises: 5582cc14fb34
Create Date: 2024-07-26 00:57:12.922909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '466a3bd8e249'
down_revision: Union[str, None] = '5582cc14fb34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
