"""Added: conversation > v3 > messages message table

Revision ID: 466dfcaebc19
Revises: 3a768843cb19
Create Date: 2024-07-21 03:58:04.473195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '466dfcaebc19'
down_revision: Union[str, None] = '3a768843cb19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
