"""added sys_opportunities_creator table

Revision ID: 46af8b93f5a1
Revises: 8a81847aa0a4
Create Date: 2024-07-03 18:00:32.685916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46af8b93f5a1'
down_revision: Union[str, None] = '8a81847aa0a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
