"""Adding model builder tables

Revision ID: 47353de4e567
Revises: 7bb1c6189cfb
Create Date: 2024-07-22 19:14:28.704795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47353de4e567'
down_revision: Union[str, None] = '7bb1c6189cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_auto_builders_model_builder_model_builders', sa.Column('uuid', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_auto_builders_model_builder_model_builders', 'uuid')
    # ### end Alembic commands ###
