"""Added: social-media > conversation > categories category table

Revision ID: 478a51aa8666
Revises: 278a0e8021f0
Create Date: 2024-07-23 21:48:29.413123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '478a51aa8666'
down_revision: Union[str, None] = '278a0e8021f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
