"""Added: conversation > v3 > categories > sub-categories sub_category table

Revision ID: 4921462cda47
Revises: b2b57f292c0d
Create Date: 2024-07-21 01:34:43.131476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4921462cda47'
down_revision: Union[str, None] = 'b2b57f292c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
