"""Added: auto-builders > model-builder > model-headers model_header table

Revision ID: 49796e1b4125
Revises: 39675937d2c0
Create Date: 2024-07-27 18:04:15.821362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49796e1b4125'
down_revision: Union[str, None] = '39675937d2c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
