"""Added: auto-builders > model-builder > model-headers model_header table

Revision ID: 4a650956c57f
Revises: 5b25d04543f8
Create Date: 2024-07-26 01:56:13.789323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a650956c57f'
down_revision: Union[str, None] = '5b25d04543f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
