"""Added: companies company table

Revision ID: 4b89f0a43639
Revises: ef86ceaa5195
Create Date: 2024-07-25 22:11:27.788956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b89f0a43639'
down_revision: Union[str, None] = 'ef86ceaa5195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
