"""Added:  > api > assignment assignment table

Revision ID: 4c5cfc62d75d
Revises: 96c810985402
Create Date: 2025-04-16 22:26:12.560655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c5cfc62d75d'
down_revision: Union[str, None] = '96c810985402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
