"""Added: admin > auto-builders > model-builder > model-fields model_field table

Revision ID: 4c9e50e29958
Revises: 41455b7f1def
Create Date: 2024-07-21 19:48:30.912877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c9e50e29958'
down_revision: Union[str, None] = '41455b7f1def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
