"""Added: customers customer table

Revision ID: 4d8800e1b3f7
Revises: bfa34cd96112
Create Date: 2024-07-22 09:16:27.368121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d8800e1b3f7'
down_revision: Union[str, None] = 'bfa34cd96112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
