"""Added: auto-builders > model-builder model_builder table

Revision ID: 4dbc5ccf435f
Revises: 2367a3a9caad
Create Date: 2024-07-26 02:28:08.175447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dbc5ccf435f'
down_revision: Union[str, None] = '2367a3a9caad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
