"""Added: conversation > v3 > categories > sub-categories > questions question table

Revision ID: 4dd66cc6c0ae
Revises: 19b9320de2e7
Create Date: 2024-07-21 03:51:19.996075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dd66cc6c0ae'
down_revision: Union[str, None] = '19b9320de2e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
