"""Added: conversation > v3 > interviews interview table

Revision ID: 4f0d43149058
Revises: 22bd0b9aee7a
Create Date: 2024-07-21 11:04:29.300290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f0d43149058'
down_revision: Union[str, None] = '22bd0b9aee7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
