"""Added: conversation > categories category table

Revision ID: 4ff65f4e1e29
Revises: e7c1d6e72bc1
Create Date: 2024-07-21 21:29:47.918542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ff65f4e1e29'
down_revision: Union[str, None] = 'e7c1d6e72bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
