"""Added: conversation > v3 > categories > sub-categories > questions question table

Revision ID: 5002de22b56f
Revises: c23a5c6e75c4
Create Date: 2024-07-18 21:10:40.619149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5002de22b56f'
down_revision: Union[str, None] = 'c23a5c6e75c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversation_v3_categories_sub_categories_questions_ibfk_2', 'conversation_v3_categories_sub_categories_questions', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('conversation_v3_categories_sub_categories_questions_ibfk_2', 'conversation_v3_categories_sub_categories_questions', 'conversation_app_v3_categories_sub_categories', ['sub_category_id'], ['id'])
    # ### end Alembic commands ###
