"""Added: conversation-app > categories category table

Revision ID: 506ddaff29b9
Revises: a6fd6fd631ca
Create Date: 2024-07-15 13:34:30.776598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '506ddaff29b9'
down_revision: Union[str, None] = 'a6fd6fd631ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='conversation_app_categories')
    op.drop_column('conversation_app_categories', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_app_categories', sa.Column('description', mysql.TEXT(), nullable=True))
    op.create_index('name', 'conversation_app_categories', ['name'], unique=True)
    # ### end Alembic commands ###
