"""Added: conversation > v3 > categories > sub-categories > questions question table

Revision ID: 5137c383acbf
Revises: 0085bfaf40cb
Create Date: 2024-07-21 10:39:32.059699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5137c383acbf'
down_revision: Union[str, None] = '0085bfaf40cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
