"""Added: conversation > v3 > categories category table

Revision ID: 5186bda6596b
Revises: 16b387ecb807
Create Date: 2024-07-20 21:19:08.967769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5186bda6596b'
down_revision: Union[str, None] = '16b387ecb807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
