"""Added: conversation > v3 > categories > sub-categories sub_category table

Revision ID: 5235144a306b
Revises: b0ef1eef3eb1
Create Date: 2024-07-21 01:13:08.771799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5235144a306b'
down_revision: Union[str, None] = 'b0ef1eef3eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
