"""Added: admin > auto-builders > model-builder model_builder table

Revision ID: 523ba475ba5d
Revises: efdaff717cf0
Create Date: 2024-07-21 19:03:00.856437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '523ba475ba5d'
down_revision: Union[str, None] = 'efdaff717cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
