"""Added: admin > auto-builders > model-builder model_builder table

Revision ID: 527ff698bc31
Revises: 9d0f172b836d
Create Date: 2024-07-21 19:09:13.910034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527ff698bc31'
down_revision: Union[str, None] = '9d0f172b836d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
