"""Added: social-media > conversation > categories category table

Revision ID: 5358d2afffe9
Revises: 0664ab902260
Create Date: 2024-07-23 21:15:04.631295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5358d2afffe9'
down_revision: Union[str, None] = '0664ab902260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
