"""Added: conversation > categories category table

Revision ID: 56a9f20c1a34
Revises: 45c2a748eb0d
Create Date: 2024-07-21 21:27:40.880605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a9f20c1a34'
down_revision: Union[str, None] = '45c2a748eb0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
