"""added sys_opportunities_creator table

Revision ID: 5965ff51759a
Revises: 64f3cf4d9315
Create Date: 2024-07-03 15:26:21.115548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5965ff51759a'
down_revision: Union[str, None] = '64f3cf4d9315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
