"""Added: auto-builders > model-builder model_builder table

Revision ID: 5b25d04543f8
Revises: 35911e49c975
Create Date: 2024-07-26 01:54:52.376853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b25d04543f8'
down_revision: Union[str, None] = '35911e49c975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
