"""Added: auto-builders > model-builder model_builder table

Revision ID: 5b65a4dd4844
Revises: 90f70b0fc9b7
Create Date: 2024-07-26 01:20:49.254430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b65a4dd4844'
down_revision: Union[str, None] = '90f70b0fc9b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
