"""Added: conversation > v3 > interviews interview table

Revision ID: 5e346d4f8cee
Revises: a18fcf74ec1d
Create Date: 2024-07-20 13:57:51.794472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e346d4f8cee'
down_revision: Union[str, None] = 'a18fcf74ec1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
