"""Added: conversation > v3 > categories category table

Revision ID: 6118c6029a50
Revises: 5186bda6596b
Create Date: 2024-07-20 21:20:15.880882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6118c6029a50'
down_revision: Union[str, None] = '5186bda6596b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
