"""added sys_opportunities_creator table

Revision ID: 64f3cf4d9315
Revises: d60e17f3e9e3
Create Date: 2024-07-03 15:19:24.048956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f3cf4d9315'
down_revision: Union[str, None] = 'd60e17f3e9e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
