"""Added: conversation > v3 > categories > sub-categories sub_category table

Revision ID: 662ebd239e9f
Revises: 96ef56166c8a
Create Date: 2024-07-21 10:41:16.763070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '662ebd239e9f'
down_revision: Union[str, None] = '96ef56166c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
