"""Added: auto-builders > model-builder > action-labels action_label table

Revision ID: 673b93d5207e
Revises: d0bcc02211f3
Create Date: 2024-07-25 21:22:57.191760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '673b93d5207e'
down_revision: Union[str, None] = 'd0bcc02211f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
