"""Added: dash > core-categories core_category table

Revision ID: 67cd6356fbb6
Revises: 2e6a0dbf86c1
Create Date: 2024-07-18 10:35:45.998079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67cd6356fbb6'
down_revision: Union[str, None] = '2e6a0dbf86c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
