"""Added: auto-builders > model-builder model_builder table

Revision ID: 6a55d724af08
Revises: 35db0033b5be
Create Date: 2024-07-26 01:24:09.211538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a55d724af08'
down_revision: Union[str, None] = '35db0033b5be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
