"""Added: conversation > categories category table

Revision ID: 6b0e91e3f1ed
Revises: 6ced1c19fd5e
Create Date: 2024-07-21 21:19:31.219029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b0e91e3f1ed'
down_revision: Union[str, None] = '6ced1c19fd5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
