"""Added: auto-builders > model-builder model_builder table

Revision ID: 6b6643efa081
Revises: 13834c93db7f
Create Date: 2024-08-21 22:14:25.454962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b6643efa081'
down_revision: Union[str, None] = '13834c93db7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
