"""Added: auto-builders > model-builder > action-labels action_label table

Revision ID: 6c0b27ec763b
Revises: d0b713c97bb4
Create Date: 2024-07-27 18:04:46.750472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c0b27ec763b'
down_revision: Union[str, None] = 'd0b713c97bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
