"""added ticketing4reest2 table

Revision ID: 6c236e6e16d1
Revises: becc45cc2e8a
Create Date: 2024-07-03 08:58:22.331478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c236e6e16d1'
down_revision: Union[str, None] = 'becc45cc2e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
