"""Added: customers customer table

Revision ID: 6c669e9ef3e0
Revises: 0c01e4e305a1
Create Date: 2024-07-22 09:41:34.479750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c669e9ef3e0'
down_revision: Union[str, None] = '0c01e4e305a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
