"""Added: conversation > categories category table

Revision ID: 6ced1c19fd5e
Revises: 148b4171222c
Create Date: 2024-07-21 21:17:19.085258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ced1c19fd5e'
down_revision: Union[str, None] = '148b4171222c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
