"""Added: conversation > v3 > categories > sub-categories sub_category table

Revision ID: 6d5f7c3a9eea
Revises: c208a5e05be1
Create Date: 2024-07-21 03:54:37.727947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d5f7c3a9eea'
down_revision: Union[str, None] = 'c208a5e05be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
