"""Added: auto-builders > model-builder model_builder table

Revision ID: 6f93bbaf4bd5
Revises: 44b1cbf0cdd1
Create Date: 2024-07-25 23:51:20.602350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f93bbaf4bd5'
down_revision: Union[str, None] = '44b1cbf0cdd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
