"""Added: admin > auto-builders > model-builder > action-labels action_label table

Revision ID: 6fa79b683e4e
Revises: 39d923b56e9e
Create Date: 2024-07-21 19:01:55.655049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa79b683e4e'
down_revision: Union[str, None] = '39d923b56e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
