"""Added: admin > auto-builders > model-builder > action-labels action_label table

Revision ID: 6fc9dbe3e173
Revises: 8ad59f73b71b
Create Date: 2024-07-21 15:38:50.824650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc9dbe3e173'
down_revision: Union[str, None] = '8ad59f73b71b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_auto_builders_model_builder_action_labels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_builder_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('actionType', sa.String(length=255), nullable=True),
    sa.Column('show', sa.String(length=255), nullable=True),
    sa.Column('status_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['model_builder_id'], ['admin_auto_builders_model_builder_model_builders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_auto_builders_model_builder_action_labels')
    # ### end Alembic commands ###
