"""Added: auto-builders > model-builder model_builder table

Revision ID: 7023fa50eaa5
Revises: c6f26111277f
Create Date: 2024-07-25 19:41:47.730454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7023fa50eaa5'
down_revision: Union[str, None] = 'c6f26111277f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_builders_model_builder_model_builders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('modelDisplayName', sa.String(length=255), nullable=True),
    sa.Column('name_singular', sa.String(length=255), nullable=True),
    sa.Column('name_plural', sa.String(length=255), nullable=True),
    sa.Column('modelURI', sa.String(length=255), nullable=True),
    sa.Column('apiEndpoint', sa.String(length=255), nullable=True),
    sa.Column('table_name_singular', sa.String(length=255), nullable=True),
    sa.Column('table_name_plural', sa.String(length=255), nullable=True),
    sa.Column('class_name', sa.String(length=255), nullable=True),
    sa.Column('createFrontendViews', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apiEndpoint'),
    sa.UniqueConstraint('modelURI'),
    sa.UniqueConstraint('table_name_plural'),
    sa.UniqueConstraint('table_name_singular'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_index('apiEndpoint', table_name='adm7dauto_builders_model_builders2_model_builder2s')
    op.drop_index('modelURI', table_name='adm7dauto_builders_model_builders2_model_builder2s')
    op.drop_index('table_name_plural', table_name='adm7dauto_builders_model_builders2_model_builder2s')
    op.drop_index('table_name_singular', table_name='adm7dauto_builders_model_builders2_model_builder2s')
    op.drop_table('adm7dauto_builders_model_builders2_model_builder2s')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adm7dauto_builders_model_builders2_model_builder2s',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('modelDisplayName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name_singular', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name_plural', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('modelURI', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('apiEndpoint', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('table_name_singular', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('table_name_plural', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('class_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status_id', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='adm7dauto_builders_model_builders2_model_builder2s_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('table_name_singular', 'adm7dauto_builders_model_builders2_model_builder2s', ['table_name_singular'], unique=True)
    op.create_index('table_name_plural', 'adm7dauto_builders_model_builders2_model_builder2s', ['table_name_plural'], unique=True)
    op.create_index('modelURI', 'adm7dauto_builders_model_builders2_model_builder2s', ['modelURI'], unique=True)
    op.create_index('apiEndpoint', 'adm7dauto_builders_model_builders2_model_builder2s', ['apiEndpoint'], unique=True)
    op.drop_table('auto_builders_model_builder_model_builders')
    # ### end Alembic commands ###
