"""added category table

Revision ID: 71357f091106
Revises: cb8d2dfe9bbf
Create Date: 2024-07-07 14:51:17.225174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '71357f091106'
down_revision: Union[str, None] = 'cb8d2dfe9bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('categories', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('categories', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_index('name', table_name='categories')
    op.drop_column('categories', 'status_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('status_id', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False))
    op.create_index('name', 'categories', ['name'], unique=True)
    op.alter_column('categories', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('categories', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('categories', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
