"""Added: auto-builders > model-builder model_builder table

Revision ID: 72020d5ecabc
Revises: 5b55fecfa620
Create Date: 2024-07-26 02:22:43.199260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72020d5ecabc'
down_revision: Union[str, None] = '5b55fecfa620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
