"""Added:  > api > email-providers emailprovider table

Revision ID: 72a2bf85e28e
Revises: e127ff63f426
Create Date: 2025-04-17 09:01:16.497601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a2bf85e28e'
down_revision: Union[str, None] = 'e127ff63f426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
