"""Added: conversation > categories category table

Revision ID: 730204788250
Revises: a2ac613b7095
Create Date: 2024-07-21 21:14:19.288197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730204788250'
down_revision: Union[str, None] = 'a2ac613b7095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_categories', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_categories', 'description')
    # ### end Alembic commands ###
