"""Added: Company company table

Revision ID: 73a88328971b
Revises: dac22131f21a
Create Date: 2025-04-16 16:27:04.295063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73a88328971b'
down_revision: Union[str, None] = 'dac22131f21a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('Number_of_employees', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'Number_of_employees')
    # ### end Alembic commands ###
