"""Added: auto-builders > model-builder > model-headers model_header table

Revision ID: 743c4eaf98b0
Revises: 08fbc26d3f82
Create Date: 2024-07-25 20:58:56.145073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '743c4eaf98b0'
down_revision: Union[str, None] = '08fbc26d3f82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_builders_model_builder_model_headers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_builder_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('isVisibleInList', sa.Integer(), nullable=True),
    sa.Column('isVisibleInSingleView', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['model_builder_id'], ['auto_builders_model_builder_model_builders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auto_builders_model_builder_model_headers')
    # ### end Alembic commands ###
