"""Added: dash > leads lead table

Revision ID: 74d6bd7fa832
Revises: d5b608c0f0bf
Create Date: 2024-07-18 11:51:24.160396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d6bd7fa832'
down_revision: Union[str, None] = 'd5b608c0f0bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
