"""Added: conversation > v3 > categories > sub-categories > questions question table

Revision ID: 76da10e62a9e
Revises: b4e80cf48b2c
Create Date: 2024-07-18 21:21:53.841764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76da10e62a9e'
down_revision: Union[str, None] = 'b4e80cf48b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'conversation_v3_categories_sub_categories_questions', 'conversation_v3_categories_sub_categories', ['sub_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation_v3_categories_sub_categories_questions', type_='foreignkey')
    # ### end Alembic commands ###
