"""Added: auto-builders > model-builder > model-fields model_field table

Revision ID: 7707dc182f4a
Revises: 743c4eaf98b0
Create Date: 2024-07-25 21:16:21.903010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7707dc182f4a'
down_revision: Union[str, None] = '743c4eaf98b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_builders_model_builder_model_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_builder_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('dataType', sa.String(length=255), nullable=True),
    sa.Column('defaultValue', sa.String(length=255), nullable=True),
    sa.Column('isVisibleInList', sa.Integer(), nullable=True),
    sa.Column('isVisibleInSingleView', sa.Integer(), nullable=True),
    sa.Column('isRequired', sa.Integer(), nullable=True),
    sa.Column('isUnique', sa.Integer(), nullable=True),
    sa.Column('dropdownSource', sa.String(length=255), nullable=True),
    sa.Column('dropdownDependsOn', sa.JSON(none_as_null=None), nullable=True),
    sa.Column('desktopWidth', sa.Integer(), nullable=True),
    sa.Column('mobileWidth', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['model_builder_id'], ['auto_builders_model_builder_model_builders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auto_builders_model_builder_model_fields')
    # ### end Alembic commands ###
