"""Added: dash > leads lead table

Revision ID: 790d5a42fa38
Revises: 74d6bd7fa832
Create Date: 2024-07-18 11:52:22.518926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790d5a42fa38'
down_revision: Union[str, None] = '74d6bd7fa832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
