"""Added: auto-builders > model-builder > model-headers model_header table

Revision ID: 799d66960517
Revises: c5b74d843261
Create Date: 2024-07-26 00:12:11.464273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '799d66960517'
down_revision: Union[str, None] = 'c5b74d843261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
