"""Added: social-media > conversation > categories category table

Revision ID: 7bb1c6189cfb
Revises: 4bfb53579104
Create Date: 2024-07-22 19:00:01.021076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bb1c6189cfb'
down_revision: Union[str, None] = '4bfb53579104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
