"""Added: conversation > v3 > categories > sub-categories > questions question table

Revision ID: 7d40dce9b8cc
Revises: d1cb79be06f3
Create Date: 2024-07-20 21:53:19.640581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d40dce9b8cc'
down_revision: Union[str, None] = 'd1cb79be06f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
