"""Added: admin > auto-builders > model-builder > action-labels action_label table

Revision ID: 7f46a2f1b0d1
Revises: 22c46375b340
Create Date: 2024-07-21 19:54:06.063691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f46a2f1b0d1'
down_revision: Union[str, None] = '22c46375b340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
