"""Added: conversation > categories category table

Revision ID: 7f7fae57cbbe
Revises: 3c04bb84f996
Create Date: 2024-07-21 21:32:31.085684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f7fae57cbbe'
down_revision: Union[str, None] = '3c04bb84f996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
