"""Added: conversation > categories category table

Revision ID: 8276eb2c81e0
Revises: 56a9f20c1a34
Create Date: 2024-07-21 21:28:06.495424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8276eb2c81e0'
down_revision: Union[str, None] = '56a9f20c1a34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
