"""Added: conversation > v3 > interviews interview table

Revision ID: 8299dd47d3a1
Revises: fb38c10d3bee
Create Date: 2024-07-21 10:40:48.042919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8299dd47d3a1'
down_revision: Union[str, None] = 'fb38c10d3bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
