"""Added: admin > auto-builders > model-builder model_builder table

Revision ID: 829bbf2a650d
Revises: 523ba475ba5d
Create Date: 2024-07-21 19:04:56.644722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '829bbf2a650d'
down_revision: Union[str, None] = '523ba475ba5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
