"""Added: auto-builders > model-builder > model-headers model_header table

Revision ID: 834badb08147
Revises: b4704542b5e5
Create Date: 2024-07-26 02:20:31.757546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '834badb08147'
down_revision: Union[str, None] = 'b4704542b5e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
