"""Added: conversation > v3 > messages message table

Revision ID: 85d4c831ebc2
Revises: effb99022e47
Create Date: 2024-07-21 10:41:02.208564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d4c831ebc2'
down_revision: Union[str, None] = 'effb99022e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
