"""Added: social-media > conversation > categories category table

Revision ID: 863d11656bb9
Revises: 08db221a8ae8
Create Date: 2024-07-22 21:10:54.225807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '863d11656bb9'
down_revision: Union[str, None] = '08db221a8ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
