"""Added: conversation > v3 > categories > sub-categories sub_category table

Revision ID: 87c9fa2332cb
Revises: f4333725aab4
Create Date: 2024-07-21 01:23:31.816943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c9fa2332cb'
down_revision: Union[str, None] = 'f4333725aab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
