"""Added: conversation > v3 > categories category table

Revision ID: 8865c528824c
Revises: cb39369648b7
Create Date: 2024-07-21 04:08:25.362960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8865c528824c'
down_revision: Union[str, None] = 'cb39369648b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
