"""Added: social-media > conversation > categories category table

Revision ID: 88683eb50ac2
Revises: 47353de4e567
Create Date: 2024-07-22 19:15:37.453523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88683eb50ac2'
down_revision: Union[str, None] = '47353de4e567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
