"""Added: conversation > v3 > categories category table

Revision ID: 8943e04e8704
Revises: 2b41de717786
Create Date: 2024-07-18 20:40:55.239925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8943e04e8704'
down_revision: Union[str, None] = '2b41de717786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
