"""added sys_opportunities_creator table

Revision ID: 8a81847aa0a4
Revises: 1f7448b0a53b
Create Date: 2024-07-03 17:59:02.010459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a81847aa0a4'
down_revision: Union[str, None] = '1f7448b0a53b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
