"""Added: auto-builders > model-builder model_builder table

Revision ID: 8b4ef1f0db6d
Revises: 9531cdd68cc1
Create Date: 2024-07-25 20:44:53.118132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4ef1f0db6d'
down_revision: Union[str, None] = '9531cdd68cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
