"""Added: conversation > v3 > categories category table

Revision ID: 8db2b9b521d4
Revises: 6118c6029a50
Create Date: 2024-07-20 21:27:29.996794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db2b9b521d4'
down_revision: Union[str, None] = '6118c6029a50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
