"""Added: conversation > v3 > categories > sub-categories > questions question table

Revision ID: 8eec0045e527
Revises: 76da10e62a9e
Create Date: 2024-07-18 21:31:54.036889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eec0045e527'
down_revision: Union[str, None] = '76da10e62a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
