"""Added: auto-builders > model-builder > action-labels action_label table

Revision ID: 9009d421f421
Revises: b348e9b3b813
Create Date: 2024-07-26 02:28:35.307325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9009d421f421'
down_revision: Union[str, None] = 'b348e9b3b813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
