"""Added: auto-builders > model-builder > model-fields model_field table

Revision ID: 904de7df7685
Revises: 799d66960517
Create Date: 2024-07-26 00:12:22.531860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '904de7df7685'
down_revision: Union[str, None] = '799d66960517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
