"""Added: auto-builders > model-builder > model-fields model_field table

Revision ID: 90f70b0fc9b7
Revises: a06797e26316
Create Date: 2024-07-26 01:04:54.466271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f70b0fc9b7'
down_revision: Union[str, None] = 'a06797e26316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
