"""Added: dash > core-categories core_category table

Revision ID: 9148cdecffb2
Revises: f3a2657d562a
Create Date: 2024-07-18 10:31:53.230569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9148cdecffb2'
down_revision: Union[str, None] = 'f3a2657d562a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
