"""added sys_opportunities_creator table

Revision ID: 91963b962ad7
Revises: 46af8b93f5a1
Create Date: 2024-07-03 18:02:05.861066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91963b962ad7'
down_revision: Union[str, None] = '46af8b93f5a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
