"""Added: conversation > v3 > categories category table

Revision ID: 919c13b9b9f6
Revises: c48c8c524937
Create Date: 2024-07-20 21:41:34.494969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '919c13b9b9f6'
down_revision: Union[str, None] = 'c48c8c524937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
