"""Added: auto-builders > model-builder model_builder table

Revision ID: 92fe0a0dccde
Revises: 45e98235f49c
Create Date: 2024-07-26 02:18:59.217246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92fe0a0dccde'
down_revision: Union[str, None] = '45e98235f49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
