"""Added: admin > auto-builders > model-builder > model-headers model_header table

Revision ID: 944af707707d
Revises: ba9df9d96d9c
Create Date: 2024-07-21 20:07:57.359624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '944af707707d'
down_revision: Union[str, None] = 'ba9df9d96d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
