"""Added: auto-builders > model-builder > model-fields model_field table

Revision ID: 94cfb2494db6
Revises: 0925edc219c7
Create Date: 2024-07-26 02:19:17.759579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94cfb2494db6'
down_revision: Union[str, None] = '0925edc219c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
