"""Added: social-media > conversation > categories category table

Revision ID: 952c5b04e1c9
Revises: 44657ef6c176
Create Date: 2024-07-22 18:57:01.553934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '952c5b04e1c9'
down_revision: Union[str, None] = '44657ef6c176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
