"""Added: auto-builders > model-builder model_builder table

Revision ID: 9531cdd68cc1
Revises: 3a2353962665
Create Date: 2024-07-25 20:42:41.560417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9531cdd68cc1'
down_revision: Union[str, None] = '3a2353962665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
