"""Added: auto-builders > model-builder model_builder table

Revision ID: 963abd42eb02
Revises: 63d6b97e9f31
Create Date: 2024-07-26 02:28:58.061200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '963abd42eb02'
down_revision: Union[str, None] = '63d6b97e9f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
