"""Added: admin > auto-builders > model-builder > model-fields model_field table

Revision ID: 97dc53b66599
Revises: 889f6c0327a9
Create Date: 2024-07-21 18:46:42.490850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97dc53b66599'
down_revision: Union[str, None] = '889f6c0327a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
