"""Added: admin > auto-builders > model-builder > model-fields model_field table

Revision ID: 9a21f5af3835
Revises: 944af707707d
Create Date: 2024-07-21 20:10:47.689288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a21f5af3835'
down_revision: Union[str, None] = '944af707707d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
