"""Added: auto-builders > model-builder > model-headers model_header table

Revision ID: a06797e26316
Revises: e2774ff8dc26
Create Date: 2024-07-26 01:04:43.347784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a06797e26316'
down_revision: Union[str, None] = 'e2774ff8dc26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
