"""Added: conversation > v3 > categories > sub-categories > questions question table

Revision ID: a06aee5a6884
Revises: 8cef4a632655
Create Date: 2024-07-20 21:45:42.282855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a06aee5a6884'
down_revision: Union[str, None] = '8cef4a632655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
