"""Added: auto-builders > model-builder model_builder table

Revision ID: a0e9048c7a29
Revises: 6c58201425b6
Create Date: 2024-07-26 02:24:39.324937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0e9048c7a29'
down_revision: Union[str, None] = '6c58201425b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
