"""Added: social-media > conversation > messages message table

Revision ID: a19eadd11329
Revises: 914d48a9d1d2
Create Date: 2024-07-27 21:15:56.770801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a19eadd11329'
down_revision: Union[str, None] = '914d48a9d1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_media_conversation_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('sub_category_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('mode', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('interview_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('question_scores', sa.Integer(), nullable=True),
    sa.Column('audio_uri', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['social_media_conversation_categories.id'], ),
    sa.ForeignKeyConstraint(['interview_id'], ['social_media_conversation_interviews.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['soc4bversation_categories_sub_categories_questions.id'], ),
    sa.ForeignKeyConstraint(['sub_category_id'], ['soc7e_media_conversation_categories_sub_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_media_conversation_messages')
    # ### end Alembic commands ###
