"""Added: admin > auto-builders > model-builder model_builder table

Revision ID: a2251ffbc295
Revises: 3bd0bcbb7e6f
Create Date: 2024-07-21 19:06:27.789948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2251ffbc295'
down_revision: Union[str, None] = '3bd0bcbb7e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
