"""Added: admin > auto-builders > model-builder > action-labels action_label table

Revision ID: a41fdf627a32
Revises: c83d65bd0f92
Create Date: 2024-07-21 19:01:03.779749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a41fdf627a32'
down_revision: Union[str, None] = 'c83d65bd0f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
