"""Added: auto-builders > model-builder > action-labels action_label table

Revision ID: a54e7f5c77d1
Revises: 34d4d1910bb9
Create Date: 2024-07-27 18:17:00.018351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a54e7f5c77d1'
down_revision: Union[str, None] = '34d4d1910bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
