"""Added: social-media > conversation > categories > sub-categories sub_category table

Revision ID: a6082636161e
Revises: c585d62f0f55
Create Date: 2024-07-23 11:59:12.141647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6082636161e'
down_revision: Union[str, None] = 'c585d62f0f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
