"""Added: admin > auto-builders > model-builder > model-fields model_field table

Revision ID: a659140cac2b
Revises: 4c9e50e29958
Create Date: 2024-07-21 19:52:07.273734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a659140cac2b'
down_revision: Union[str, None] = '4c9e50e29958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
