"""Add WordConfidence

Revision ID: a88b3a90ccb3
Revises: 26fbf5dbf04c
Create Date: 2024-07-18 00:32:14.053228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a88b3a90ccb3'
down_revision: Union[str, None] = '26fbf5dbf04c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_v2_word_confidences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('start_time_seconds', sa.Integer(), nullable=True),
    sa.Column('start_time_nanos', sa.Integer(), nullable=True),
    sa.Column('end_time_seconds', sa.Integer(), nullable=True),
    sa.Column('end_time_nanos', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['conversation_v2_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_v2_word_confidences')
    # ### end Alembic commands ###
