"""Added: conversation > v3 > categories category table

Revision ID: a95d2dc5c009
Revises: c329641c0cab
Create Date: 2024-07-20 21:12:00.670566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95d2dc5c009'
down_revision: Union[str, None] = 'c329641c0cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
