"""Added: conversation-app > categories > sub-categories > questions question table

Revision ID: ab27e741d605
Revises: debaf0fe2328
Create Date: 2024-07-15 14:27:51.526985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab27e741d605'
down_revision: Union[str, None] = 'debaf0fe2328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
