"""Added: auto-builders > model-builder > model-headers model_header table

Revision ID: ac4fc76eb8f4
Revises: 963abd42eb02
Create Date: 2024-07-26 02:29:07.363293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4fc76eb8f4'
down_revision: Union[str, None] = '963abd42eb02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
