"""Added: conversation > v3 > categories category table

Revision ID: ade16731ecc4
Revises: e99a06ccf570
Create Date: 2024-07-18 20:23:21.526019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade16731ecc4'
down_revision: Union[str, None] = 'e99a06ccf570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
