"""Added: conversation > v3 > categories > sub-categories sub_category table

Revision ID: b0ef1eef3eb1
Revises: 0bbd426facaf
Create Date: 2024-07-21 00:51:33.486001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ef1eef3eb1'
down_revision: Union[str, None] = '0bbd426facaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
