"""Added: conversation > v3 > categories > sub-categories sub_category table

Revision ID: b2b57f292c0d
Revises: 37a7c8f9de65
Create Date: 2024-07-21 01:33:30.228896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b57f292c0d'
down_revision: Union[str, None] = '37a7c8f9de65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
