"""Added: auto-builders > model-builder > model-fields model_field table

Revision ID: b348e9b3b813
Revises: 0bf8cb234836
Create Date: 2024-07-26 02:28:26.431804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b348e9b3b813'
down_revision: Union[str, None] = '0bf8cb234836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
