"""Added: auto-builders > model-builder > action-labels action_label table

Revision ID: b36c270313a6
Revises: 2aa207ff1fa3
Create Date: 2024-07-26 02:29:30.784696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b36c270313a6'
down_revision: Union[str, None] = '2aa207ff1fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
