"""Added: conversation > v3 > interviews interview table

Revision ID: b40674b3d5c8
Revises: 5e346d4f8cee
Create Date: 2024-07-20 13:58:44.431139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b40674b3d5c8'
down_revision: Union[str, None] = '5e346d4f8cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
