"""Added: auto-builders > model-builder model_builder table

Revision ID: b4704542b5e5
Revises: 803b3e75755e
Create Date: 2024-07-26 02:20:22.699790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4704542b5e5'
down_revision: Union[str, None] = '803b3e75755e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
