"""Added: conversation > v3 > categories category table

Revision ID: b4e80cf48b2c
Revises: 2a3425ebec52
Create Date: 2024-07-18 21:19:45.065829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e80cf48b2c'
down_revision: Union[str, None] = '2a3425ebec52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
