"""Added: social-media > conversation > categories > sub-categories > questions question table

Revision ID: b5869321a036
Revises: fe0f6d59c2ac
Create Date: 2024-08-21 21:54:21.079281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5869321a036'
down_revision: Union[str, None] = 'fe0f6d59c2ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
