"""Added: auto-builders > model-builder > action-labels action_label table

Revision ID: b735a80bd3f1
Revises: ccc06014ffa8
Create Date: 2024-07-25 21:21:54.313187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b735a80bd3f1'
down_revision: Union[str, None] = 'ccc06014ffa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'auto_builders_model_builder_action_labels', 'auto_builders_model_builder_model_builders', ['model_builder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auto_builders_model_builder_action_labels', type_='foreignkey')
    # ### end Alembic commands ###
