"""Added: conversation > v3 > categories > sub-categories sub_category table

Revision ID: b7b3c8815da7
Revises: b6dd0c6c6f04
Create Date: 2024-07-21 21:42:03.223518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7b3c8815da7'
down_revision: Union[str, None] = 'b6dd0c6c6f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
