"""Added: social-media > conversation > categories > sub-categories > questions question table

Revision ID: b83631591fe5
Revises: 38f89fac4e8c
Create Date: 2024-08-21 22:27:05.102915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b83631591fe5'
down_revision: Union[str, None] = '38f89fac4e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
