"""Added: customers customer table

Revision ID: b89d635e2d4d
Revises: b0bc6cc7599f
Create Date: 2024-07-22 09:37:22.601637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b89d635e2d4d'
down_revision: Union[str, None] = 'b0bc6cc7599f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
