"""Added: auto-builders > model-builder model_builder table

Revision ID: b92caf443069
Revises: bb9a2008bfb6
Create Date: 2024-07-25 23:34:30.226126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b92caf443069'
down_revision: Union[str, None] = 'bb9a2008bfb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
