"""Added: users user table

Revision ID: ba3ca91a9bd6
Revises: c12ab4e41d8b
Create Date: 2024-07-26 00:21:30.816997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba3ca91a9bd6'
down_revision: Union[str, None] = 'c12ab4e41d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
