"""Added: social-media > conversation > interviews interview table

Revision ID: bc52bd669b85
Revises: 14f70205158a
Create Date: 2024-08-11 21:23:48.232938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bc52bd669b85'
down_revision: Union[str, None] = '14f70205158a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_media_conversation_interviews', sa.Column('current_question_id', sa.Integer(), nullable=True))
    op.drop_constraint('social_media_conversation_interviews_ibfk_2', 'social_media_conversation_interviews', type_='foreignkey')
    op.create_foreign_key(None, 'social_media_conversation_interviews', 'soc4bversation_categories_sub_categories_questions', ['current_question_id'], ['id'])
    op.drop_column('social_media_conversation_interviews', 'question_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_media_conversation_interviews', sa.Column('question_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'social_media_conversation_interviews', type_='foreignkey')
    op.create_foreign_key('social_media_conversation_interviews_ibfk_2', 'social_media_conversation_interviews', 'soc4bversation_categories_sub_categories_questions', ['question_id'], ['id'])
    op.drop_column('social_media_conversation_interviews', 'current_question_id')
    # ### end Alembic commands ###
