"""Added: auto-builders > model-builder model_builder table

Revision ID: bd3a47f85fb9
Revises: 6b6643efa081
Create Date: 2024-08-21 22:16:42.053272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3a47f85fb9'
down_revision: Union[str, None] = '6b6643efa081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
