"""added sys_opportunities_creator table

Revision ID: be84fd86eac2
Revises: bf41eeb58ef8
Create Date: 2024-07-03 17:34:00.289549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be84fd86eac2'
down_revision: Union[str, None] = 'bf41eeb58ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
