"""added sys_opportunities_creator table

Revision ID: bf41eeb58ef8
Revises: 337f17724db7
Create Date: 2024-07-03 17:32:01.439103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf41eeb58ef8'
down_revision: Union[str, None] = '337f17724db7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
