"""Added: auto-builders > model-builder > model-fields model_field table

Revision ID: c12ab4e41d8b
Revises: d647e7533f35
Create Date: 2024-07-26 00:13:24.364646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c12ab4e41d8b'
down_revision: Union[str, None] = 'd647e7533f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
