"""Added: social-media > conversation > categories > sub-categories > questions question table

Revision ID: c3350f6633ea
Revises: b5869321a036
Create Date: 2024-08-21 21:56:10.627054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3350f6633ea'
down_revision: Union[str, None] = 'b5869321a036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
