"""Added: admin > auto-builders > model-builder > model-headers model_header table

Revision ID: c3a46a6a30cf
Revises: cbe418907fc9
Create Date: 2024-07-21 18:57:36.995075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c3a46a6a30cf'
down_revision: Union[str, None] = 'cbe418907fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_auto_builders_model_builder_model_headers', 'isVisibleInList',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('admin_auto_builders_model_builder_model_headers', 'isVisibleInSingleView',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_auto_builders_model_builder_model_headers', 'isVisibleInSingleView',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('admin_auto_builders_model_builder_model_headers', 'isVisibleInList',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
