"""Added: social-media > conversation > categories > sub-categories sub-category table

Revision ID: c4f7e0770f71
Revises: 863d11656bb9
Create Date: 2024-07-22 21:31:47.163020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4f7e0770f71'
down_revision: Union[str, None] = '863d11656bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_media_conversation_categories_sub-categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sub_category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('learn_instructions', sa.Text(), nullable=True),
    sa.Column('status_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'admin_auto_builders_model_builder_model_builders', ['apiEndpoint'])
    op.create_unique_constraint(None, 'admin_auto_builders_model_builder_model_builders', ['modelURI'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_auto_builders_model_builder_model_builders', type_='unique')
    op.drop_constraint(None, 'admin_auto_builders_model_builder_model_builders', type_='unique')
    op.drop_table('social_media_conversation_categories_sub-categories')
    # ### end Alembic commands ###
