"""Added: social-media > conversation > categories > sub-categories sub_category table

Revision ID: c585d62f0f55
Revises: 1625bdbfbd0b
Create Date: 2024-07-23 11:58:28.917489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c585d62f0f55'
down_revision: Union[str, None] = '1625bdbfbd0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_media_conversation_categories_sub_categories', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'social_media_conversation_categories_sub_categories', 'social_media_conversation_categories', ['category_id'], ['id'])
    op.drop_column('social_media_conversation_categories_sub_categories', 'sub_category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_media_conversation_categories_sub_categories', sa.Column('sub_category_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'social_media_conversation_categories_sub_categories', type_='foreignkey')
    op.drop_column('social_media_conversation_categories_sub_categories', 'category_id')
    # ### end Alembic commands ###
