"""Added: auto-builders > model-builder model_builder table

Revision ID: c5b74d843261
Revises: 69a66c253263
Create Date: 2024-07-26 00:11:24.735658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b74d843261'
down_revision: Union[str, None] = '69a66c253263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
