"""Added: admin > auto-builders > model-builder > action-labels action_label table

Revision ID: c83d65bd0f92
Revises: c3a46a6a30cf
Create Date: 2024-07-21 18:59:12.244542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c83d65bd0f92'
down_revision: Union[str, None] = 'c3a46a6a30cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_auto_builders_model_builder_action_labels', 'show',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_auto_builders_model_builder_action_labels', 'show',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
