"""Added: auto-builders > model-builder > model-fields model_field table

Revision ID: c967c69e6df4
Revises: e1f8560fec10
Create Date: 2024-07-26 02:24:57.692267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c967c69e6df4'
down_revision: Union[str, None] = 'e1f8560fec10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
