"""Added: auto-builders > model-builder model_builder table

Revision ID: c9924dc1e493
Revises: df1e886c698d
Create Date: 2024-07-26 01:40:14.348358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9924dc1e493'
down_revision: Union[str, None] = 'df1e886c698d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
