"""Added: auto-builders > model-builder > model-fields model_field table

Revision ID: c9cc15aebc9b
Revises: 834badb08147
Create Date: 2024-07-26 02:20:40.728482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9cc15aebc9b'
down_revision: Union[str, None] = '834badb08147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
