"""Added: conversation > v3 > categories > sub-categories > questions question table

Revision ID: cb39369648b7
Revises: df92fff9132d
Create Date: 2024-07-21 04:07:40.797612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb39369648b7'
down_revision: Union[str, None] = 'df92fff9132d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
