"""added ticket table

Revision ID: cb8d2dfe9bbf
Revises: b04ad1f76e69
Create Date: 2024-07-07 14:39:54.720968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb8d2dfe9bbf'
down_revision: Union[str, None] = 'b04ad1f76e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
