"""Added: admin > auto-builders > model-builders2 model_builder2 table

Revision ID: cdaea5b18a37
Revises: 9d93470da958
Create Date: 2024-07-25 00:47:45.389404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdaea5b18a37'
down_revision: Union[str, None] = '9d93470da958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adm7dauto_builders_model_builders2_model_builder2s',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('modelDisplayName', sa.String(length=255), nullable=True),
    sa.Column('name_singular', sa.String(length=255), nullable=True),
    sa.Column('name_plural', sa.String(length=255), nullable=True),
    sa.Column('modelURI', sa.String(length=255), nullable=True),
    sa.Column('apiEndpoint', sa.String(length=255), nullable=True),
    sa.Column('table_name_singular', sa.String(length=255), nullable=True),
    sa.Column('table_name_plural', sa.String(length=255), nullable=True),
    sa.Column('class_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apiEndpoint'),
    sa.UniqueConstraint('modelURI'),
    sa.UniqueConstraint('table_name_plural'),
    sa.UniqueConstraint('table_name_singular')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adm7dauto_builders_model_builders2_model_builder2s')
    # ### end Alembic commands ###
