"""Added: conversation > v3 > categories > sub-categories sub_category table

Revision ID: d06bf2abb8dc
Revises: 3732432c516d
Create Date: 2024-07-18 21:14:28.531981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd06bf2abb8dc'
down_revision: Union[str, None] = '3732432c516d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
