"""Added: auto-builders > model-builder > action-labels action_label table

Revision ID: d0bcc02211f3
Revises: b735a80bd3f1
Create Date: 2024-07-25 21:22:21.399527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0bcc02211f3'
down_revision: Union[str, None] = 'b735a80bd3f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
