"""Added: social-media > conversation > categories > sub-categories sub_category table

Revision ID: d1bc44e50bac
Revises: c3350f6633ea
Create Date: 2024-08-21 22:01:23.797739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1bc44e50bac'
down_revision: Union[str, None] = 'c3350f6633ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
