"""Added: conversation > v3 > categories > sub-categories > questions question table

Revision ID: d1cb79be06f3
Revises: a06aee5a6884
Create Date: 2024-07-20 21:45:59.033895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1cb79be06f3'
down_revision: Union[str, None] = 'a06aee5a6884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
