"""Added: social-media > conversation > categories category table

Revision ID: d3e56d3f2076
Revises: 802027f0f8ac
Create Date: 2024-07-22 18:40:51.855444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e56d3f2076'
down_revision: Union[str, None] = '802027f0f8ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
