"""Added: auto-builders > model-builder model_builder table

Revision ID: d61fc7a91f08
Revises: 0736ee91d9fd
Create Date: 2024-07-26 01:22:57.947753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd61fc7a91f08'
down_revision: Union[str, None] = '0736ee91d9fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
