"""Added: auto-builders > model-builder > model-headers model_header table

Revision ID: d647e7533f35
Revises: 2d07f664a753
Create Date: 2024-07-26 00:13:15.582470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd647e7533f35'
down_revision: Union[str, None] = '2d07f664a753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
