"""Added: conversation > v3 > categories category table

Revision ID: d735138ea2e4
Revises: e95d6e721a06
Create Date: 2024-07-20 21:13:32.291190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd735138ea2e4'
down_revision: Union[str, None] = 'e95d6e721a06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
