"""added sys_opportunities_creator table

Revision ID: d7ffd441a63f
Revises: 10c149ca9482
Create Date: 2024-07-03 17:57:44.698014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7ffd441a63f'
down_revision: Union[str, None] = '10c149ca9482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
