"""Added: admin > auto-builders > model-builder > model-fields model_field table

Revision ID: da5a663eeb4b
Revises: fef159bbfbf5
Create Date: 2024-07-21 21:54:47.325127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'da5a663eeb4b'
down_revision: Union[str, None] = 'fef159bbfbf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_auto_builders_model_builder_model_fields', 'desktopWidth',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('admin_auto_builders_model_builder_model_fields', 'mobileWidth',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_auto_builders_model_builder_model_fields', 'mobileWidth',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('admin_auto_builders_model_builder_model_fields', 'desktopWidth',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
