"""Added: Company company table

Revision ID: dac22131f21a
Revises: 9ec37e348b3a
Create Date: 2025-04-16 13:21:13.182247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac22131f21a'
down_revision: Union[str, None] = '9ec37e348b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'address')
    # ### end Alembic commands ###
