"""Added: social-media > conversation > categories > sub-categories > questions question table

Revision ID: db224c439d35
Revises: 1eb1db3b280b
Create Date: 2024-08-24 15:26:31.024391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db224c439d35'
down_revision: Union[str, None] = '1eb1db3b280b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
