"""Added: social-media > conversation > categories category table

Revision ID: ddb48f84e6ea
Revises: c434843cf0c9
Create Date: 2024-07-22 23:51:21.681591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb48f84e6ea'
down_revision: Union[str, None] = 'c434843cf0c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
