"""Added: conversation > categories > sub-categories sub_category table

Revision ID: de442dc35875
Revises: da5a663eeb4b
Create Date: 2024-07-21 21:55:11.073853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de442dc35875'
down_revision: Union[str, None] = 'da5a663eeb4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
