"""Added: conversation-app > categories > sub-categories > questions question table

Revision ID: debaf0fe2328
Revises: faca2e11f31b
Create Date: 2024-07-15 14:07:48.678600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'debaf0fe2328'
down_revision: Union[str, None] = 'faca2e11f31b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_app_categories_sub_categories_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_app_category_id', sa.Integer(), nullable=True),
    sa.Column('conversation_app_categories_sub_category_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=255), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_app_categories_sub_category_id'], ['conversation_app_categories_sub_categories.id'], ),
    sa.ForeignKeyConstraint(['conversation_app_category_id'], ['conversation_app_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_app_categories_sub_categories_questions')
    # ### end Alembic commands ###
