"""Added: conversation > v3 > interviews interview table

Revision ID: df5806ab0a7b
Revises: 5147c377e819
Create Date: 2024-07-20 13:20:44.789732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df5806ab0a7b'
down_revision: Union[str, None] = '5147c377e819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
