"""Added: conversation > v3 > categories > sub-categories sub_category table

Revision ID: df92fff9132d
Revises: f661c3773a35
Create Date: 2024-07-21 04:06:23.951740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df92fff9132d'
down_revision: Union[str, None] = 'f661c3773a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
