"""Added:  > api > email-providers emailprovider table

Revision ID: e127ff63f426
Revises: 17435a6850db
Create Date: 2025-04-17 09:00:59.778981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e127ff63f426'
down_revision: Union[str, None] = '17435a6850db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
