"""Added: auto-builders > model-builder model_builder table

Revision ID: e12850120fc3
Revises: 7023fa50eaa5
Create Date: 2024-07-25 20:35:46.497575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e12850120fc3'
down_revision: Union[str, None] = '7023fa50eaa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
