"""Added: auto-builders > model-builder > model-headers model_header table

Revision ID: e1f8560fec10
Revises: a0e9048c7a29
Create Date: 2024-07-26 02:24:48.714810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f8560fec10'
down_revision: Union[str, None] = 'a0e9048c7a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
