"""Added: admin > auto-builders > model-builder model_builder table

Revision ID: e520fe528166
Revises: 2db7b05c2466
Create Date: 2024-07-21 14:47:25.317664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e520fe528166'
down_revision: Union[str, None] = '2db7b05c2466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
