"""Added: conversation > categories category table

Revision ID: e7c1d6e72bc1
Revises: b35a7db3166a
Create Date: 2024-07-21 21:29:09.726697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c1d6e72bc1'
down_revision: Union[str, None] = 'b35a7db3166a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
