"""Added: conversation > v3 > categories category table

Revision ID: e95d6e721a06
Revises: a95d2dc5c009
Create Date: 2024-07-20 21:13:16.654557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e95d6e721a06'
down_revision: Union[str, None] = 'a95d2dc5c009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
