"""Added: social-media > conversation > messages message table

Revision ID: ebe1bd6426fa
Revises: 4d845135e54f
Create Date: 2024-07-27 21:30:33.477080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe1bd6426fa'
down_revision: Union[str, None] = '4d845135e54f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
