"""Added: conversation > v3 > messages message table

Revision ID: ecfed25c17f3
Revises: 466dfcaebc19
Create Date: 2024-07-21 04:05:00.028370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecfed25c17f3'
down_revision: Union[str, None] = '466dfcaebc19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
