"""Added: conversation > categories category table

Revision ID: eda71c7f1fc6
Revises: 4ff65f4e1e29
Create Date: 2024-07-21 21:30:42.320775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda71c7f1fc6'
down_revision: Union[str, None] = '4ff65f4e1e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
