"""Added: social-media > conversation > messages message table

Revision ID: edd2790cc060
Revises: 2f86dac39811
Create Date: 2024-07-28 02:42:31.958542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd2790cc060'
down_revision: Union[str, None] = '2f86dac39811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
