"""Added: conversation > v3 > categories > sub-categories > questions question table

Revision ID: ef031bc27d5c
Revises: 6ab1ffa84975
Create Date: 2024-07-20 22:18:25.931258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef031bc27d5c'
down_revision: Union[str, None] = '6ab1ffa84975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
