"""Added: dash > core-categories core_category table

Revision ID: ef337c36516a
Revises: 9148cdecffb2
Create Date: 2024-07-18 10:34:55.421369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef337c36516a'
down_revision: Union[str, None] = '9148cdecffb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
