"""Added: admin > auto-builders > model-builder > model-headers model_header table

Revision ID: efdaff717cf0
Revises: 6fa79b683e4e
Create Date: 2024-07-21 19:02:11.360544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efdaff717cf0'
down_revision: Union[str, None] = '6fa79b683e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
