"""Added: conversation > v3 > categories > sub-categories sub_category table

Revision ID: effb99022e47
Revises: 8299dd47d3a1
Create Date: 2024-07-21 10:40:52.815091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'effb99022e47'
down_revision: Union[str, None] = '8299dd47d3a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
