"""Added: conversation > v3 > categories category table

Revision ID: f2c9a8f3e4ab
Revises: 6707453d8756
Create Date: 2024-07-18 19:13:38.408845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2c9a8f3e4ab'
down_revision: Union[str, None] = '6707453d8756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
