"""Added: dash > core-categories core_category table

Revision ID: f3a2657d562a
Revises: 640d6350e41b
Create Date: 2024-07-18 10:27:16.462180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a2657d562a'
down_revision: Union[str, None] = '640d6350e41b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dash_core_categories', sa.Column('sub_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dash_core_categories', 'conversation_v2_categories_sub_categories', ['sub_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dash_core_categories', type_='foreignkey')
    op.drop_column('dash_core_categories', 'sub_category_id')
    # ### end Alembic commands ###
