"""Added: conversation > v3 > categories > sub-categories sub_category table

Revision ID: f4333725aab4
Revises: 8e01b544268b
Create Date: 2024-07-21 01:18:38.441918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4333725aab4'
down_revision: Union[str, None] = '8e01b544268b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
