"""Added: conversation > v2 > categories category table

Revision ID: f5f6a1e60b63
Revises: 454aef09b29e
Create Date: 2024-07-18 17:00:08.935651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f6a1e60b63'
down_revision: Union[str, None] = '454aef09b29e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
