"""Added: conversation > v3 > interviews interview table

Revision ID: f661c3773a35
Revises: ecfed25c17f3
Create Date: 2024-07-21 04:05:48.864428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f661c3773a35'
down_revision: Union[str, None] = 'ecfed25c17f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
