"""Added: auto-builders > model-builder model_builder table

Revision ID: fa2fbdba55c7
Revises: 6c9ccf7a91cd
Create Date: 2024-07-26 02:16:34.145179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa2fbdba55c7'
down_revision: Union[str, None] = '6c9ccf7a91cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
