"""Added: conversation > v3 > messages > word-confidences word_confidence table

Revision ID: fb38c10d3bee
Revises: 5137c383acbf
Create Date: 2024-07-21 10:40:28.289084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb38c10d3bee'
down_revision: Union[str, None] = '5137c383acbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
