"""Added: conversation-app > categories category table

Revision ID: fb5f3f3604b6
Revises: 506ddaff29b9
Create Date: 2024-07-15 13:36:06.658259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5f3f3604b6'
down_revision: Union[str, None] = '506ddaff29b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
