"""Added: social-media > conversation > categories > sub-categories > questions question table

Revision ID: fe0f6d59c2ac
Revises: bc52bd669b85
Create Date: 2024-08-21 21:52:57.984837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0f6d59c2ac'
down_revision: Union[str, None] = 'bc52bd669b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
