"""Added: conversation > categories category table

Revision ID: fef159bbfbf5
Revises: b7b3c8815da7
Create Date: 2024-07-21 21:43:10.242105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef159bbfbf5'
down_revision: Union[str, None] = 'b7b3c8815da7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
